version: '3.5'

services:
  # nginx:
  #   image: nginx:1.21-alpine
  #   env_file:
  #     - .env
  #   ports:
  #     - "${NGINX_HOST_PORT}:80"
  #   volumes:
  #     - ./nginx/templates:/etc/nginx/templates
  #   depends_on:
  #     - web
  redis:
    hostname: gateway_redis
    container_name: safe_gateway_redis
    image: redis:6-alpine
    volumes:
      - ./data/redis:/data
    env_file:
      - .env
    # ports:
    #   - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - gnosis.safe

  web:
    hostname: gateway_web
    container_name: safe_gateway_web
    build: .
    env_file:
      - .env
    ports:
      - "6003:8000"
    depends_on:
      - redis
    networks:
      - gnosis.safe

networks:
  gnosis.safe:
    name: gnosis.safe
    driver: bridge

